title: Huang Shaoze's Homepage
page-top-title: Huang Shaoze
top-section-bg-text: Materials Science and Engineering
home-subtitle: Huang Shaoze&ensp;|&ensp;黄绍泽
copyright-text: '&copy; Huang Shaoze 2022-2026. All Rights Reserved.'
